### ISSUE TITLE
use HTML in tiptool

### ISSUE THREAD

**Issue by breizhwave** [monaye/nova-tippy-field#2]
Hi, very good plugin, any idea on how to display html as it is in tip tool ? currently displays tags

**Comment by breizhwave** [comment]
nice one

   ->tippyOptions([  'allowHTML' => 'true'])

**Comment by monaye** [comment]
@breizhwave 
yes. should work with using `tippyOptions`. 
https://github.com/monaye/nova-tippy-field#tippyoptions
